### ISSUE TITLE
Fix Go Report Card Issues

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#130] opened 2024-03-29 22:19 UTC
Fix all issues identified in our latest [Go Report Card](https://goreportcard.com/report/github.com/Boeing/config-file-validator) for v1.6.0

**Comment by ashish111333** [comment] 2024-04-08 06:17
I would like to work on this,Pls assign it to me.

**Comment by ccoVeille** [comment] 2024-04-08 06:32
@HakanVardarr started to implement it in #131

**Comment by ccoVeille** [comment] 2024-04-09 05:21
@kehoecj could you assign the issue to @HakanVardarr ?

Also, is there any other issue that @ashish111333 could look at?

**Comment by ccoVeille** [comment] 2024-04-09 17:32
GitHub…

OK, thanks

**Comment by HakanVardarr** [comment] 2024-04-10 07:45
> > @kehoecj could you assign the issue to @HakanVardarr ?
> > Also, is there any other issue that @ashish111333 could look at?
> 
> I tired but it doesn't seem like I can until @HakanVardarr makes a comment on the issue

😀

**Comment by ccoVeille** [comment] 2024-04-14 08:49
I think the issue is now closed as #131 was merged

**Closed** 2024-04-15 20:31 UTC
Labels: good first issue, help wanted
